=== mite-standard/mite_extras/src/mite_extras/schema/entry.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "1.0",
  "type": "object",
  "title": "Minimum Information about a Tailoring Enzyme/Maturase Data Standard",
  "additionalProperties": false,
  "required": [
    "accession",
    "quality",
    "status",
    "changelog",
    "enzyme",
    "reactions"
  ],
  "properties": {
    "accession": {
      "title": "MITE accession number/identifier.",
      "$ref": "#/$defs/accession"
    },
    "quality": {
      "title": "Track quality of entry.",
      "$ref": "#/$defs/quality"
    },
    "status": {
      "title": "Track status of entry.",
      "$ref": "#/$defs/status"
    },
    "retirementReasons": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "changelog": {
      "title": "Log tracking changes in entry.",
      "$ref": "https://meta.secondarymetabolites.org/schemas/common/changelog.json"
    },
    "enzyme": {
      "title": "(Meta)data about the enzyme described by entry.",
      "$ref": "definitions/enzyme.json"
    },
    "reactions": {
      "title": "One or more reactions associated with enzyme.",
      "type": "array",
      "items": {
        "$ref": "definitions/reactions.json"
      },
      "minItems": 1
    },
    "comment": {
      "title": "Any additional information about this entry",
      "type": "string"
    },
    "attachments": {
      "title": "Additional information as key:value pairs.",
      "type": "object"
    }
  },
  "$defs": {
    "accession": {
      "type": "string",
      "pattern": "^MITE\\d{7,7}$"
    },
    "quality": {
      "type": "string",
      "enum": [
        "questionable",
        "low",
        "medium",
        "high"
      ]
    },
    "status": {
      "type": "string",
      "enum": [
        "pending",
        "embargoed",
        "active",
        "retired"
      ]
    }
  }
}

=== mite-standard/mite_extras/tests/test_schema/example_valid.json
{
  "accession": "MITE0000000",
  "quality": "high",
  "status": "pending",
  "retirementReasons": [
    "Test retirement reasons"
  ],
  "changelog": {
    "releases": [
      {
        "version": "next",
        "date": "2024-03-21",
        "entries": [
          {
            "contributors": ["AAAAAAAAAAAAAAAAAAAAAAAA"],
            "reviewers": ["BBBBBBBBBBBBBBBBBBBBBBBB"],
            "date": "2024-03-21",
            "comment": "Initial entry."
          }
        ]
      }
    ]
  },
  "comment": "Test comment",
  "attachments": {
    "1": "test attachment 1",
    "2": "test attachment 2"
  },
  "enzyme": {
    "name": "McjB",
    "description": "Lassopeptide ATP-dependent protease (B-protein, cysteine protease-like)",
    "databaseIds": [
      "uniprot:Q9X2V8",
      "genpept:AAD28495.1"
    ],
    "auxiliaryEnzymes": [
      {
        "name": "McjC",
        "description": "Lassopeptide ATP-dependent lactam synthetase. Required for precursor cleavage function.",
        "databaseIds": [
          "uniprot:Q9X2V9",
          "genpept:AAD28496.1"
        ]
      }
    ],
    "references": [
      "doi:10.1128/jb.181.8.2659-2662.1999",
      "doi:10.1002/cbic.201200016"
    ]
  },
  "reactions": [
    {
      "tailoring": [
        "Hydrolysis"
      ],
      "description": "ATP-dependent N-terminal cleavage of leader peptide, resulting in immature intermediate core peptide.",
      "reactionSMARTS": {
        "reactionSMARTS": "[#6:1]-[#6:2](-[#6:3])-[#6:4]-[#6@H:5](-[#7:6]-[#6:7](=[O:8])-[#6@H:9](-[#6:10]-[#6:11]-[#6:12](-[#7:13])=[O:14])-[#7:15]-[#6:16](=[O:17])-[#6@H:18](-[#6:19]-[#8:20])-[#7:21]-[#6:22](=[O:23])-[#6@H:24](-[#6:25])-[#7:26]-[#6:27](=[O:28])-[#6@H:29](-[#6:30]-[#8:31])-[#7:32]-[#6:33](=[O:34])-[#6@@H:35](-[#7:36])-[#6:37]-[#6:38]-[#6:39]-[#6:40]-[#7:41])-[#6:42](=[O:43])-[#7:44]-[#6@@H:45](-[#6@@H:62](-[#6:63])-[#8:64])-[#6:46](=[O:47])-[#7:48]-[#6@@H:49](-[#6:50]-[#6:51]-[#6:52]-[#6:53]-[#7:54])-[#6:55](=[O:56])-[#7:57]-[#6:58]-[#6:59](-[#7:61])=[O:60]>>[#7:57]-[#6:58]-[#6:59](-[#7:61])=[O:60]",
        "isIterative": false,
        "evidence": [
          {
            "evidenceCode": [
              "Heterologous expression",
              "Site-directed mutagenesis"
            ],
            "references": [
              "doi:10.1002/cbic.201200016",
              "doi:10.1021/ja910191u"
            ]
          }
        ]
      },
      "reactions": [
        {
          "substrate": "CC[C@H](C)[C@H](NC(=O)CNC(=O)[C@@H](NC(=O)[C@H](Cc1ccccc1)NC(=O)[C@H](Cc1ccc(O)cc1)NC(=O)[C@H](CCC(=O)O)NC(=O)[C@@H]1CCCN1C(=O)[C@@H](NC(=O)[C@H](Cc1c[nH]cn1)NC(=O)CNC(=O)[C@H](C)NC(=O)CNC(=O)CNC(=O)[C@H](CCCCN)NC(=O)[C@@H](NC(=O)[C@H](CC(C)C)NC(=O)[C@H](CCC(N)=O)NC(=O)[C@H](CO)NC(=O)[C@H](C)NC(=O)[C@H](CO)NC(=O)[C@H](CCCCN)NC(=O)[C@H](CCCCN)NC(=O)[C@@H](NC(=O)[C@H](CCC(N)=O)NC(=O)[C@@H](NC(=O)[C@@H](NC(=O)CNC(=O)[C@H](CCCCN)NC(=O)[C@H](C)NC(=O)[C@@H]1CCCN1C(=O)[C@H](CO)NC(=O)[C@@H]1CCCN1C(=O)[C@@H](NC(=O)[C@H](CC(N)=O)NC(=O)[C@H](CC(N)=O)NC(=O)[C@H](CCCCN)NC(=O)[C@H](CCCCN)NC(=O)CNC(=O)[C@H](CO)NC(=O)[C@H](CO)NC(=O)[C@H](CC(C)C)NC(=O)[C@H](CCCCN)NC(=O)[C@H](CC(N)=O)NC(=O)[C@H](Cc1ccccc1)NC(=O)[C@H](Cc1c[nH]cn1)NC(=O)[C@H](Cc1ccccc1)NC(=O)[C@H](Cc1c[nH]cn1)NC(=O)[C@H](CCCCN)NC(=O)[C@@H](NC(=O)[C@@H](N)CCSC)[C@@H](C)CC)C(C)C)C(C)C)[C@@H](C)CC)[C@@H](C)CC)[C@@H](C)O)C(C)C)C(C)C)C(=O)NCC(=O)N[C@H](C(=O)N1CCC[C@H]1C(=O)N[C@H](C(=O)N[C@@H](CO)C(=O)N[C@@H](Cc1ccccc1)C(=O)N[C@@H](Cc1ccc(O)cc1)C(=O)NCC(=O)O)[C@@H](C)CC)[C@@H](C)O",
          "products": [
            "CC[C@H](C)[C@H](NC(=O)CNC(=O)[C@@H](NC(=O)[C@H](Cc1ccccc1)NC(=O)[C@H](Cc1ccc(O)cc1)NC(=O)[C@H](CCC(=O)O)NC(=O)[C@@H]1CCCN1C(=O)[C@@H](NC(=O)[C@H](Cc1c[nH]cn1)NC(=O)CNC(=O)[C@H](C)NC(=O)CNC(=O)CN)C(C)C)C(C)C)C(=O)NCC(=O)N[C@H](C(=O)N1CCC[C@H]1C(=O)N[C@H](C(=O)N[C@@H](CO)C(=O)N[C@@H](Cc1ccccc1)C(=O)N[C@@H](Cc1ccc(O)cc1)C(=O)NCC(=O)O)[C@@H](C)CC)[C@@H](C)O"
          ],
          "isBalanced": false,
          "isIntermediate": true,
          "description": "Precursor cleavage of the McjA precursor peptide, resulting in the intermediate core peptide before macrolactam formation.",
          "evidence": [
            {
              "evidenceCode": [
                "Heterologous expression",
                "Site-directed mutagenesis"
              ],
              "references": [
                "doi:10.1002/cbic.201200016",
                "doi:10.1021/ja910191u"
              ]
            }
          ]
        }
      ]
    }
  ]
}
